version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled:  false
  method-complexity:
    enabled: true
    config:
      threshold: 11
  method-count:
    enabled: true
    config:
      threshold: 50
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4

plugins:
  pylint:
    enabled: true

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "script/"
- "**/test/"
- "**/vendor/"