version: '2'
services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alegre_test
  xlm_r_bert_base_nli_stsb_mean_tokens:
    environment:
      BOILERPLATE_ENV: test
      FLASK_ENV: test
      FLASK_DEBUG: "true"
      MODEL_NAME: meantokens
  indian_sbert:
    environment:
      BOILERPLATE_ENV: test
      FLASK_ENV: test
      FLASK_DEBUG: "true"
      MODEL_NAME: indiansbert
  model_test:
    build: .
    command: ["make", "run_model"]
    volumes:
      - ".:/app"
    depends_on:
      - redis
    env_file:
      - .env_file
    environment:
      BOILERPLATE_ENV: test
      FLASK_ENV: test
      FLASK_DEBUG: "true"
      MODEL_CLASS: SharedModelTest
      MODEL_KEY: shared-model-test
  alegre:
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - model_test
      - xlm_r_bert_base_nli_stsb_mean_tokens
      - indian_sbert
    environment:
      BOILERPLATE_ENV: test
      FLASK_ENV: test
      FLASK_DEBUG: "true"
