"""image sha256 non nullable

Revision ID: 0acf2526e02f
Revises: e495509fad52
Create Date: 2023-11-30 17:04:11.666888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0acf2526e02f'
down_revision = 'e495509fad52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', sa.Column('sha256', sa.String(length=64, _expect_unicode=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', sa.Column('sha256', sa.String(length=64, _expect_unicode=True), nullable=False))
    # ### end Alembic commands ###
