"""empty message

Revision ID: 0cea38d6b231
Revises: bea9f3bcf92b
Create Date: 2021-07-13 17:46:07.805282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cea38d6b231'
down_revision = 'bea9f3bcf92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hash_value', postgresql.BIT(length=256), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audios_pkey')
    )
    op.create_index('ix_audios_url', 'audios', ['url'], unique=False)
    op.create_index('ix_audios_hash_value', 'audios', ['hash_value'], unique=False)
    op.create_index('ix_audios_doc_id', 'audios', ['doc_id'], unique=True)
    op.create_index('ix_audios_context', 'audios', ['context'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audios_context', table_name='audios')
    op.drop_index('ix_audios_doc_id', table_name='audios')
    op.drop_index('ix_audios_hash_value', table_name='audios')
    op.drop_index('ix_audios_url', table_name='audios')
    op.drop_table('audios')
    # ### end Alembic commands ###
