"""empty message

Revision ID: 29e18ef5546e
Revises: d9a1aab0cbaa
Create Date: 2021-11-04 15:50:45.658486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29e18ef5546e'
down_revision = 'd9a1aab0cbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('chromaprint_fingerprint', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audios', 'chromaprint_fingerprint')
    # ### end Alembic commands ###
