"""empty message

Revision ID: 34aa3e711acc
Revises: a3cb92addcc9
Create Date: 2021-10-05 19:23:51.999778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34aa3e711acc'
down_revision = 'd9a1aab0cbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('chromaprint_fingerprint', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('audios', sa.Column('hash_value', postgresql.BIT(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audios', sa.Column('hash_value', postgresql.BIT(length=128), nullable=False))
    op.drop_column('audios', 'chromaprint_fingerprint')
    # ### end Alembic commands ###
