"""empty message

Revision ID: 4b657abd7dc3
Revises: ae9896b94f1b
Create Date: 2021-06-10 20:54:25.788063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b657abd7dc3'
down_revision = 'ae9896b94f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_hashes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hash_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='context_hashes_pkey')
    )
    op.create_index('ix_context_hashes_hash_key', 'context_hashes', ['hash_key'], unique=False)
    op.create_index('ix_context_hashes_context', 'context_hashes', ['context'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_context_hashes_context', table_name='context_hashes')
    op.drop_index('ix_context_hashes_hash_key', table_name='context_hashes')
    op.drop_table('context_hashes')
    # ### end Alembic commands ###
