"""empty message

Revision ID: 5ca7ffe8941e
Revises: 29e18ef5546e
Create Date: 2021-11-18 18:16:26.367304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ca7ffe8941e'
down_revision = '29e18ef5546e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('data_types', postgresql.ARRAY(sa.String(length=255, _expect_unicode=True)), nullable=True),
    sa.Column('status', sa.String(length=255, _expect_unicode=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=500, _expect_unicode=True), nullable=False),
    sa.Column('data_type_id', sa.String(length=500, _expect_unicode=True), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_data_type_id'), 'nodes', ['data_type_id'], unique=False)
    op.create_index('node_id_constraint', 'nodes', ['data_type', 'data_type_id'], unique=True)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edge_type', sa.String(length=500, _expect_unicode=True), nullable=False),
    sa.Column('edge_weight', sa.Float(), nullable=False),
    sa.Column('edge_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('edge_source_target_graph', 'edges', ['source_id', 'target_id', 'graph_id'], unique=True)
    op.create_index(op.f('ix_edges_graph_id'), 'edges', ['graph_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_graph_id'), table_name='edges')
    op.drop_index('edge_source_target_graph', table_name='edges')
    op.drop_table('edges')
    op.drop_index('node_id_constraint', table_name='nodes')
    op.drop_index(op.f('ix_nodes_data_type_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_table('graphs')
    # ### end Alembic commands ###
