"""empty message

Revision ID: 72fdd32f1a84
Revises: 0cea38d6b231
Create Date: 2021-07-29 20:14:46.130469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72fdd32f1a84'
down_revision = '0cea38d6b231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hash_value', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'hash_value')
    # ### end Alembic commands ###
