"""update key length on image

Revision ID: 774d0d537e69
Revises: 5e823fb0eaaa
Create Date: 2024-04-03 17:26:39.130788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774d0d537e69'
down_revision = '5e823fb0eaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'sha256',
               existing_type=sa.String(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('images', 'doc_id',
               existing_type=sa.String(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'sha256',
               existing_type=sa.String(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('images', 'doc_id',
               existing_type=sa.String(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###