"""add tmk flag on video

Revision ID: 9401ff8a031b
Revises: 774d0d537e69
Create Date: 2024-05-17 17:23:18.933056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9401ff8a031b'
down_revision = '774d0d537e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('tmk_file_downloaded', sa.Boolean(), nullable=True))
    op.execute('UPDATE videos SET tmk_file_downloaded = TRUE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'tmk_file_downloaded')
    # ### end Alembic commands ###