"""add indices

Revision ID: a836b0be6123
Revises: 774d0d537e69
Create Date: 2024-05-20 15:45:54.338200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a836b0be6123'
down_revision = '774d0d537e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create partial index for team_id
    op.execute('''
    CREATE INDEX ix_videos_team_id_partial
    ON videos ((context->>'team_id'))
    WHERE context->>'team_id' IS NOT NULL;
    ''')

    # Create partial index for has_custom_id
    op.execute('''
    CREATE INDEX ix_videos_has_custom_id_partial
    ON videos ((context->>'has_custom_id'))
    WHERE context->>'has_custom_id' IS NOT NULL;
    ''')

    # Create partial index for team_id
    op.execute('''
    CREATE INDEX ix_audios_team_id_partial
    ON audios ((context->>'team_id'))
    WHERE context->>'team_id' IS NOT NULL;
    ''')

    # Create partial index for has_custom_id
    op.execute('''
    CREATE INDEX ix_audios_has_custom_id_partial
    ON audios ((context->>'has_custom_id'))
    WHERE context->>'has_custom_id' IS NOT NULL;
    ''')

    # Create partial index for team_id
    op.execute('''
    CREATE INDEX ix_images_team_id_partial
    ON images ((context->>'team_id'))
    WHERE context->>'team_id' IS NOT NULL;
    ''')

    # Create partial index for has_custom_id
    op.execute('''
    CREATE INDEX ix_images_has_custom_id_partial
    ON images ((context->>'has_custom_id'))
    WHERE context->>'has_custom_id' IS NOT NULL;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop partial indexes
    op.drop_index('ix_videos_team_id_partial', table_name='videos')
    op.drop_index('ix_videos_has_custom_id_partial', table_name='videos')

    # Drop partial indexes
    op.drop_index('ix_audios_team_id_partial', table_name='audios')
    op.drop_index('ix_audios_has_custom_id_partial', table_name='audios')

    # Drop partial indexes
    op.drop_index('ix_images_team_id_partial', table_name='images')
    op.drop_index('ix_images_has_custom_id_partial', table_name='images')

    # ### end Alembic commands ###
