"""Add DocId to Image

Revision ID: ae9896b94f1b
Revises: 8490ccc2bf87
Create Date: 2021-01-22 22:55:33.662005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import engine_from_config
from sqlalchemy.engine import reflection

#shimmed in from https://stackoverflow.com/questions/24082542/check-if-a-table-column-exists-in-the-database-using-sqlalchemy-and-alembic
def _table_has_column(table, column):
    config = op.get_context().config
    engine = engine_from_config(
        config.get_section(config.config_ini_section), prefix='sqlalchemy.')
    insp = reflection.Inspector.from_engine(engine)
    has_column = False
    for col in insp.get_columns(table):
        if column not in col['name']:
            continue
        has_column = True
    return has_column

# revision identifiers, used by Alembic.
revision = 'ae9896b94f1b'
down_revision = '8490ccc2bf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_has_column('images', 'doc_id'):
        op.add_column('images', sa.Column('doc_id', sa.String(length=64, _expect_unicode=True), nullable=True))
        op.create_index(op.f('ix_images_doc_id'), 'images', ['doc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_has_column('images', 'doc_id'):
        op.drop_index(op.f('ix_images_doc_id'), table_name='images')
        op.drop_column('images', 'doc_id')
    # ### end Alembic commands ###
