"""empty message

Revision ID: bea9f3bcf92b
Revises: 4b657abd7dc3
Create Date: 2021-06-10 20:54:25.788063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bea9f3bcf92b'
down_revision = '4b657abd7dc3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_context_hashes_context', table_name='context_hashes')
    op.drop_index('ix_context_hashes_hash_key', table_name='context_hashes')
    op.drop_table('context_hashes')
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=255, _expect_unicode=True), nullable=False),
    sa.Column('folder', sa.String(length=255, _expect_unicode=True), nullable=False),
    sa.Column('filepath', sa.String(length=255, _expect_unicode=True), nullable=False),
    sa.Column('url', sa.String(length=255, _expect_unicode=True), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_context', 'videos', ['context'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_videos_doc_id'), 'videos', ['doc_id'], unique=False)
    op.create_index(op.f('ix_videos_url'), 'videos', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_url'), table_name='videos')
    op.drop_index(op.f('ix_videos_doc_id'), table_name='videos')
    op.drop_index('ix_videos_context', table_name='videos')
    op.drop_table('videos')
    op.create_table('context_hashes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hash_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='context_hashes_pkey')
    )
    op.create_index('ix_context_hashes_hash_key', 'context_hashes', ['hash_key'], unique=False)
    op.create_index('ix_context_hashes_context', 'context_hashes', ['context'], unique=False)
    # ### end Alembic commands ###
