"""empty message

Revision ID: c2622ac44992
Revises: 5ca7ffe8941e
Create Date: 2021-12-10 16:59:55.329068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2622ac44992'
down_revision = '5ca7ffe8941e'
branch_labels = None
depends_on = None


def upgrade():
    print('here at c2622ac44992')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('graphs', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('audios', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graphs', 'start_time')
    op.drop_column('graphs', 'end_time')
    op.drop_column('images', 'created_at')
    op.drop_column('audios', 'created_at')
    op.drop_column('videos', 'created_at')
    # ### end Alembic commands ###
