"""Initial migration.

Revision ID: c6374e82e4ae
Revises: 
Create Date: 2021-01-27 12:44:36.987889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6374e82e4ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64, _expect_unicode=True), nullable=False),
    sa.Column('phash', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=255, _expect_unicode=True), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_images_context', 'images', ['context'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_images_phash'), 'images', ['phash'], unique=False)
    op.create_index(op.f('ix_images_sha256'), 'images', ['sha256'], unique=False)
    op.create_index(op.f('ix_images_url'), 'images', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_url'), table_name='images')
    op.drop_index(op.f('ix_images_sha256'), table_name='images')
    op.drop_index(op.f('ix_images_phash'), table_name='images')
    op.drop_index('ix_images_context', table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
