-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 29bf11d13689a0a9a895c41eb3591c7e942d377d
    hooks:
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
        args:
        - --exclude=pytx/docs/*,pytx/build/*
        - --ignore=W291
